import { PortfolioItem, MarketType, Account } from "@/types";

export const CASH_TICKER = "__CASH__";

export const initialAccounts: Account[] = [
  { id: "acc1", name: "키움증권", cash: 500000 },
  { id: "acc2", name: "토스증권", cash: 300000 },
];

export const initialPortfolio: PortfolioItem[] = [
  // 현금 항목
  {
    id: "cash1",
    user_id: "user1",
    account_id: "acc1",
    ticker: CASH_TICKER,
    name: "현금",
    market: "KR" as MarketType,
    target_ratio: 10,
    current_quantity: 0,
    avg_price: 500000,
    current_price: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: "cash2",
    user_id: "user1",
    account_id: "acc1",
    ticker: CASH_TICKER,
    name: "현금",
    market: "US" as MarketType,
    target_ratio: 5,
    current_quantity: 0,
    avg_price: 10000,
    current_price: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: "cash3",
    user_id: "user1",
    account_id: "acc2",
    ticker: CASH_TICKER,
    name: "현금",
    market: "KR" as MarketType,
    target_ratio: 5,
    current_quantity: 0,
    avg_price: 300000,
    current_price: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: "1",
    user_id: "user1",
    account_id: "acc1",
    ticker: "005930.KS",
    name: "삼성전자",
    market: "KR",
    target_ratio: 30,
    current_quantity: 100,
    avg_price: 65000,
    current_price: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    user_id: "user1",
    account_id: "acc2",
    ticker: "AAPL",
    name: "Apple",
    market: "US",
    target_ratio: 40,
    current_quantity: 10,
    avg_price: 150,
    current_price: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    user_id: "user1",
    account_id: "acc1",
    ticker: "069500.KS",
    name: "KODEX 200",
    market: "KR",
    target_ratio: 20,
    current_quantity: 30,
    avg_price: 32000,
    current_price: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    user_id: "user1",
    account_id: "acc2",
    ticker: "MSFT",
    name: "Microsoft",
    market: "US",
    target_ratio: 10,
    current_quantity: 5,
    avg_price: 380,
    current_price: undefined,
    created_at: new Date().toISOString(),
  },
];
